# Generated by Django 3.1.6 on 2021-02-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_used_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('shipped', 'shipped'), ('arrived', 'arrived')], default='ordered', max_length=20),
        ),
    ]
