# Generated by Django 3.1.6 on 2021-02-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210212_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipped',
            new_name='shipped_date',
        ),
    ]
