# Generated by Django 3.1.7 on 2021-03-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
