# Generated by Django 3.1.7 on 2021-04-01 14:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productreview_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
