# Generated by Django 3.1.7 on 2021-04-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210401_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
